pankajmouriyakong/shared-actions-pankaj

.github/dependabot.yml
.github/imageList.yml
.github/scripts/sync_images.sh
.github/workflows/imagePullThrough.yml
security-actions/scan-docker-image/action.yml
security-actions/semgrep/action.yml

Updated the POC

---

renovate.json
security-actions/scan-docker-image/action.yml

Renovate poc

---

.github/scripts/sync_images.sh
.github/workflows/docker-image-scan.yml
.github/workflows/imagePullThrough.yml
security-actions/scan-docker-image/action.yml

Update existing code to ECR Private

---

.github/workflows/mirroring.yml

multi platform builds

---

.github/build/docker/security-image-matrix.yml
.github/workflows/mirroring.yml
renovate.json

add comment

---

.github/workflows/mirroring.yml
login-aws-cloud/action.yml
security-actions/scan-docker-image/action.yml
security-actions/semgrep/action.yml

Separate aws login

---

.github/build/docker/security-image-matrix.yml
.github/workflows/mirroring.yml
.github/workflows/trivy-db-mirror.yml
renovate.json
security-actions/build/dockerfiles/trivy.Dockerfile
security-actions/scan-docker-image/run-trivy/action.yml

remove trivy db from image

---

README.md
security-actions/scan-docker-image/action.yml
security-actions/semgrep/action.yml

Internal test 3

---

security-actions/scan-docker-image/action.yml
security-actions/semgrep/action.yml

Test feat 2

---

security-actions/scan-docker-image/action.yml
security-actions/semgrep/action.yml

Test feat 3

---

security-actions/scan-docker-image/action.yml
security-actions/semgrep/action.yml

Test feat 102

---

security-actions/semgrep/action.yml

feat(semgrep): update semgrep

---

security-actions/sca/action.yml
security-actions/semgrep/action.yml

Test feat 105

---

security-actions/scan-rust/action.yml
security-actions/semgrep/action.yml

Feat demo test 1

---

security-actions/sign-docker-image/action.yml

feat(sign-docker-image): update sign-docker image

---

.github/workflows/ci.yml
.github/workflows/release.yml

fix(ci): update filter file change step to exclude .md README .jpeg

---

security-actions/scan-docker-image/action.yml
security-actions/scan-rust/action.yml
security-actions/semgrep/README.md

Test main 104

---

security-actions/sca/action.yml
security-actions/scan-docker-image/README.md
security-actions/scan-rust/README.md
security-actions/semgrep/action.yml

Test main 106

---

security-actions/sca/README.md

fix(sca): update readme

---

security-actions/sca/action.yml

feat(sca): update action.yml

---

security-actions/scan-rust/README.md
security-actions/semgrep/README.md

Test main 109 1

---

security-actions/semgrep/action.yml

fix(semgrep): update action.yml

---

security-actions/semgrep/action.yml

fix(semgrep): update semgrep workflow

---

.github/workflows/ci.yml

feat(ci): update CI workflow

---

.github/workflows/release.yml

feat(release): update release workflow

---

package.json
pnpm-lock.yaml

Feat changes main 116

---

.github/workflows/ci.yml

chore(ci): test ci for commitlint on base branch

---

.github/workflows/ci.yml

chore(ci): run commitlint on main branch as well

---

security-actions/sca/action.yml
security-actions/scan-docker-image/action.yml

chore(ci): update version

---

.github/workflows/release.yml
code-build-actions/build-js-sdk/CHANGELOG.md
code-build-actions/build-js-sdk/package.json
code-check-actions/lua-lint/CHANGELOG.md
code-check-actions/lua-lint/package.json
code-check-actions/rust-lint/CHANGELOG.md
code-check-actions/rust-lint/package.json
lerna.json
pr-previews/cleanup/CHANGELOG.md
pr-previews/cleanup/package.json
pr-previews/up-to-date/CHANGELOG.md
pr-previews/up-to-date/package.json
pr-previews/validate/CHANGELOG.md
pr-previews/validate/package.json
security-actions/sca/CHANGELOG.md
security-actions/sca/package.json
security-actions/scan-docker-image/CHANGELOG.md
security-actions/scan-docker-image/action.yml
security-actions/scan-docker-image/package.json
security-actions/scan-rust/CHANGELOG.md
security-actions/scan-rust/package.json
security-actions/semgrep/CHANGELOG.md
security-actions/semgrep/package.json
security-actions/sign-docker-image/CHANGELOG.md
security-actions/sign-docker-image/package.json
slack-actions/workflow-notification/CHANGELOG.md
slack-actions/workflow-notification/package.json

chore(release): update slack message

---

.github/workflows/release.yml

chore(release): remove explicit checkout step

---

security-actions/semgrep/action.yml

chore(release): update semgrep release

---

.github/workflows/ci.yml
.github/workflows/release.yml

chore(ci): test slack message

---

security-actions/semgrep/action.yml

fix(semgrep): update semgrep version

---

.github/workflows/release.yml

fix(ci,release): update slack  version

---

security-actions/semgrep/action.yml

fix(semgrep): update semgrep

---

.github/workflows/release.yml
security-actions/semgrep/action.yml

fix(semgrep,ci): update semgrep

---

.github/workflows/release.yml

fix(ci): update release

---

.github/workflows/ci.yml
.github/workflows/release.yml

fix(ci): update slack notif

---

security-actions/scan-docker-image/action.yml

fix(semgrep): update semgrep notif

---

.github/workflows/release.yml

fix(release): create new release

---

security-actions/scan-docker-image/action.yml

feat(scan-docker-image): update trivy version

---

package.json

chore(deps): udpate package.json

---

security-actions/scan-docker-image/action.yml

feat(scan-docker-image): update trivy image version

---

.github/workflows/semgrep.yml
security-actions/semgrep/action.yml

feat(ci): update semgrep image

---

renovate.json
security-actions/semgrep/run-semgrep/action.yml

feat(ci): test ecr mirror
